name: Create Release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'

    - name: Publish
      run: |
        dotnet publish src/ForeverOnline/ForeverOnline.csproj --configuration Release --output ./publish/ForeverOnline /p:PublishProfile=SingleFile
        dotnet publish src/ForeverOnline.Launcher/ForeverOnline.Launcher.csproj --configuration Release --output ./publish/ForeverOnline.Launcher /p:PublishProfile=SingleFile

    - name: Zip files
      run: |
        mkdir -p publish/ForeverOnline/app
        find publish/ForeverOnline -maxdepth 1 -type f -exec mv {} publish/ForeverOnline/app \;
        mv publish/ForeverOnline.Launcher/* publish/ForeverOnline
        find publish/ForeverOnline -name "*.pdb" -type f -delete
        zip -r ForeverOnline.zip publish/ForeverOnline

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Upload Release Asset
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./ForeverOnline.zip
        asset_name: ForeverOnline.zip
        asset_content_type: application/zip
